from __future__ import annotations

import logging
from functools import cache
from typing import TYPE_CHECKING

import httpx
from starlette.responses import Response

from ..settings import get_settings
from . import status

if TYPE_CHECKING:
    from collections.abc import Mapping
    from pathlib import Path

_logger = logging.getLogger(__name__)


class AstroPageProxyResponse(Response):
    """
    In production, will read the matching static HTML page generated by `astro build`.
    In development, will act as an HTTP proxy to the content served by `astro dev`.
    """

    media_type = "text/html"

    def __init__(
        self,
        astro_page: str,
        status_code: int = status.HTTP_200_OK,
        headers: Mapping[str, str] | None = None,
    ):
        self.astro_page = astro_page

        super().__init__(
            content=self._get_page_content_from_astro(),
            status_code=status_code,
            headers=headers,
        )

    def _get_page_content_from_astro(self) -> bytes:
        settings = get_settings()
        match settings.environment:
            case "production":
                astro_build_folder = settings.astro_build_folder
                astro_html_page_path = (
                    astro_build_folder / self.astro_page.strip("/") / "index.html"
                )
                return _get_astro_page_from_build_folder(
                    astro_html_page_path, astro_page=self.astro_page
                )

            case "development":
                astro_dev_url = str(settings.astro_dev_url).removesuffix("/")
                target_astro_url = f"{astro_dev_url}{self.astro_page}"
                http_client = _get_dev_astro_proxy_http_client()
                astro_html_page_response = http_client.get(target_astro_url)
                astro_html_page_response.raise_for_status()
                _logger.debug(
                    "Reading HTML page '%s' from Astro: '%s'",
                    self.astro_page,
                    target_astro_url,
                )
                return self._process_astro_dev_html_page(
                    astro_html_page_response.content, astro_dev_url=astro_dev_url
                )
            case _:
                raise ValueError(f"Unknown app_mode '{settings.app_mode}'")

    @staticmethod
    def _process_astro_dev_html_page(html_page: bytes, *, astro_dev_url: str) -> bytes:
        # If this looks like an horrible hack...
        # ...it's because it is! 😅
        absolute_url_prefix = astro_dev_url.encode()
        for prefix in (
            b'"/@vite/',
            b'"/@fs/',
            b'"/@id/',
            b'"/src-frontend/',
            b'"/node_modules/',
            b'"/favicon-',
            b'"/assets/',
        ):
            html_page = html_page.replace(
                prefix, b'"' + absolute_url_prefix + prefix[1:]
            )
        # html_page = html_page.replace(
        #     b'renderer-url="/node_modules/',
        #     b'renderer-url="' + absolute_url_prefix + b"/node_modules/",
        # )
        return html_page


@cache
def _get_dev_astro_proxy_http_client() -> httpx.Client:
    return httpx.Client()


@cache  # let's cache these when we run in "production" mode
def _get_astro_page_from_build_folder(
    astro_html_page_path: "Path",
    *,
    astro_page: str,  # only used for logging
) -> bytes:
    _logger.debug(
        "Reading HTML page '%s' from Astro: '%s'",
        astro_page,
        astro_html_page_path,
    )
    try:
        return astro_html_page_path.read_bytes()
    except FileNotFoundError as err:
        raise ValueError(f"File not found: {astro_html_page_path}: {err}") from err
