from __future__ import annotations

import logging
from functools import cache
from typing import TYPE_CHECKING

import httpx
from starlette.responses import StreamingResponse

from ..settings import get_settings
from . import status

if TYPE_CHECKING:
    from collections.abc import AsyncIterator, Mapping

_logger = logging.getLogger(__name__)


class AstroPageProxyResponse(StreamingResponse):
    """
    In production, will read the matching static HTML page generated by `astro build`.
    In development, will act as an HTTP proxy to the content served by `astro dev`.
    """

    media_type = "text/html"

    def __init__(
        self,
        astro_page: str,
        status_code: int = status.HTTP_200_OK,
        headers: Mapping[str, str] | None = None,
    ):
        self.astro_page = astro_page

        super().__init__(
            content=self._get_stream_from_astro(),
            status_code=status_code,
            headers=headers,
        )

    async def _get_stream_from_astro(self) -> AsyncIterator[bytes]:
        settings = get_settings()
        match settings.environment:
            case "production":
                yield b"TODO"  # TODO: read the matching HTML file
            case "development":
                astro_dev_url = str(settings.astro_dev_url)
                target_astro_url = f"{astro_dev_url.removesuffix('/')}{self.astro_page}"
                http_client = _get_dev_astro_proxy_http_client()
                async with http_client.stream("GET", target_astro_url) as response:
                    async for chunk in response.aiter_bytes():
                        yield chunk
                _logger.debug(
                    f"HTML page '{self.astro_page}' was read from Astro: {response.url}"
                )
            case _:
                raise ValueError(f"Unknown app_mode '{settings.app_mode}'")


@cache
def _get_dev_astro_proxy_http_client() -> httpx.AsyncClient:
    return httpx.AsyncClient()
