# fly.toml file generated for zakuchess on 2022-12-08T19:51:13Z

app = "zakuchess"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  DJANGO_SETTINGS_MODULE = "project.settings.production"
  DATABASE_URL = "sqlite:////zakuchess_sqlite_dbs/zakuchess.dev.sqlite3"
  ALLOWED_HOSTS = "zakuchess.com,zakuchess.fly.dev"
  CSRF_TRUSTED_ORIGINS = "https://zakuchess.fly.dev"
  PORT = "8080"
  # from Docker we see non-HTTPS requests; it's ok, Fly.io does manage the TLS layer for us at an higher level:
  SECURE_SSL_REDIRECT = "" 

[mounts]
  source="zakuchess_sqlite_dbs"
  destination="/zakuchess_sqlite_dbs"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "5s"
    interval = "5s"
    restart_limit = 0
    timeout = "2s"

[[statics]]
  guest_path = "/app/staticfiles"
  url_prefix = "/static/"
