[tool.poetry]
name = "zakuchess"
version = "0.1.0"
description = ""
authors = ["Olivier Philippon <olivier@dunsap.com>"]

[tool.poetry.dependencies]
python = "^3.10"
Django = "^4.1.3"
django-environ = "^0.9.0"
gunicorn = "^20.1.0"
django-alive = "^1.2.1"
chess = "^1.9.3"
jinja2 = "^3.1.2"
whitenoise = "^6.2.0"
django-htmx = "^1.13.0"

[tool.poetry.group.dev.dependencies]
black = "^22.10.0"
isort = "^5.10.1"
ruff = "^0.0.141"
mypy = "^0.991"
pytest = "^7.2.0"
django-types = "^0.16.0"
pytest-django = "^4.5.2"
pre-commit = "^2.20.0"
ipython = "^8.6.0"
djlint = "^1.19.7"

[tool.black]
# @link https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html
line-length = 119
target-version = ['py310']

[tool.isort]
# @link https://pycqa.github.io/isort/docs/configuration/options.html
py_version = 310
profile = "black"
line_length = 119
multi_line_output = 3
known_first_party = ["apps"]
combine_as_imports = true

[tool.ruff]
# @link https://github.com/charliermarsh/ruff#options
line-length = 119
target-version = "py310"
exclude = [
     'src/project/settings',
]
[tool.ruff.per-file-ignores]
"bin/scripts/download_assets.py" = ["E501"]

[tool.djlint]
# @link https://www.djlint.com/docs/configuration/
profile = "jinja"
blank_line_before_tag = "block,macro"
use_gitignore = true

[tool.mypy]
# @link https://mypy.readthedocs.io/en/stable/config_file.html#using-a-pyproject-toml
python_version = "3.10"
mypy_path = "src/"
exclude = [
    '^src/project/settings/.*\.py$',
    '^src/apps/[^/]+/migrations/.*\.py$',
]
[[tool.mypy.overrides]]
module = "environ"
ignore_missing_imports = true

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "--reuse-db"
DJANGO_SETTINGS_MODULE = "project.settings.test"

[build-system]
requires = ["poetry-core>=1.2.0"]
build-backend = "poetry.core.masonry.api"
