[tool.poetry]
name = "zakuchess"
version = "0.1.0"
description = ""
authors = ["Olivier Philippon <olivier@dunsap.com>"]

[tool.poetry.dependencies]
python = "^3.10"
Django = "^4.1.3"
django-environ = "^0.9.0"
gunicorn = "^20.1.0"
django-alive = "^1.2.1"
chess = "^1.9.3"
jinja2 = "^3.1.2"
django-ninja = "^0.19.1"

[tool.poetry.group.dev.dependencies]
black = "^22.10.0"
isort = "^5.10.1"
ruff = "^0.0.141"
mypy = "^0.991"
pytest = "^7.2.0"
django-types = "^0.16.0"
pytest-django = "^4.5.2"
pre-commit = "^2.20.0"
ipython = "^8.6.0"

[tool.black]
line-length = 119
target-version = ['py310']

[tool.isort]
py_version = 310
profile = "black"
line_length = 119
multi_line_output = 3
known_first_party = ["apps"]
combine_as_imports = true

[tool.ruff]
line-length = 119
target-version = "py310"
exclude = [
     'src/project/settings',
]

[tool.mypy]
# @link https://mypy.readthedocs.io/en/stable/config_file.html#using-a-pyproject-toml
python_version = "3.10"
mypy_path = "src/"
exclude = [
    '^src/project/settings/.*\.py$',
    '^src/apps/[^/]+/migrations/.*\.py$',
]
[[tool.mypy.overrides]]
module = "environ"
ignore_missing_imports = true
[[tool.mypy.overrides]]
module = "django_unicorn.*"
ignore_missing_imports = true

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "--reuse-db"
DJANGO_SETTINGS_MODULE = "project.settings.test"

[build-system]
requires = ["poetry-core>=1.2.0"]
build-backend = "poetry.core.masonry.api"
