[tool.poetry]
name = "zakuchess"
version = "0.1.0"
description = "A daily chess challenge, where pieces are heroic-fantasy characters."
license = "GPL-3.0-or-later"
authors = ["Olivier Philippon <olivier@dunsap.com>"]
homepage = "https://github.com/olivierphi/zakuchess"

[tool.poetry.dependencies]
python = "^3.11"
Django = "^4.1.3"
gunicorn = "^20.1.0"
django-alive = "^1.2.1"
chess = "^1.9.3"
django-htmx = "^1.13.0"
dominate = "^2.7.0"
dj-database-url = "^2.1.0"
requests = "^2.31.0"
django-axes = {extras = ["ipware"], version = "^6.1.1"}
whitenoise = "^6.5.0"

[tool.poetry.group.dev.dependencies]
python-dotenv = "^1.0.0"
black = "^22.10.0"
isort = "5.12.0"
ruff = "0.0.286"
mypy = "1.5.1"
pre-commit = "^2.20.0"
ipython = "^8.6.0"
types-requests = "^2.31.0.2"

[tool.poetry.group.test.dependencies]
pytest = "^7.2.0"
pytest-django = "^4.5.2"

[tool.black]
# @link https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html
line-length = 119
target-version = ['py311']

[tool.isort]
# @link https://pycqa.github.io/isort/docs/configuration/options.html
py_version = 311
profile = "black"
line_length = 119
multi_line_output = 3
known_first_party = ["apps"]
combine_as_imports = true

[tool.ruff]
# @link https://github.com/charliermarsh/ruff#options
line-length = 119
target-version = "py311"
ignore = ["E501"]
exclude = [
    'src/project/settings',
]
[tool.ruff.per-file-ignores]
"src/lib/chess_engines/sunfish/sunfish.py" = ["F841", "F821"]

[tool.mypy]
# @link https://mypy.readthedocs.io/en/stable/config_file.html#using-a-pyproject-toml
python_version = "3.11"
mypy_path = "src/"
exclude = [
    '^src/project/settings/.*\.py$',
    '^src/apps/[^/]+/migrations/.*\.py$',
    '^src/lib/chess_engines/[^/]+/.*\.py$',
]
[[tool.mypy.overrides]]
module = "django.*"
ignore_missing_imports = true
[[tool.mypy.overrides]]
module = "environ"
ignore_missing_imports = true
[[tool.mypy.overrides]]
module = "dominate.*"
ignore_missing_imports = true

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "--reuse-db"
DJANGO_SETTINGS_MODULE = "project.settings.test"

[build-system]
requires = ["poetry-core>=1.2.0"]
build-backend = "poetry.core.masonry.api"
