# Generated by Django 5.2.6 on 2025-09-20 18:03
from __future__ import annotations

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: list[str] = []

    operations = [
        migrations.CreateModel(
            name="DailyChallenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lookup_key",
                    models.CharField(
                        help_text="e.g. '2021-10-01', or just '10-01' for challenges that can be re-used from a year to the next",
                        max_length=20,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        help_text="e.g. 'lichess-0009B'",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "pending"), (1, "published"), (2, "archived")],
                        default=0,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fen", models.CharField(max_length=90)),
                ("character_id_by_square", models.JSONField(editable=False, null=True)),
                (
                    "bot_first_move",
                    models.CharField(
                        help_text="uses UCI notation, e.g. 'e2e4'",
                        max_length=5,
                        null=True,
                    ),
                ),
                (
                    "bot_depth",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="The depth of the bot's search. 1 is a good value for an 'easy enough' daily challenge.",
                    ),
                ),
                (
                    "player_simulated_depth",
                    models.PositiveSmallIntegerField(
                        default=5,
                        help_text="The depth of the player's simulated search. 5 is a good value for modeling a 'casual' chess player (like myself ^_^).",
                    ),
                ),
                ("intro_turn_speech_square", models.CharField(max_length=2, null=True)),
                (
                    "starting_advantage",
                    models.IntegerField(
                        help_text="positive number means the human player has an advantage, negative number means the bot has an advantage",
                        null=True,
                    ),
                ),
                (
                    "solution",
                    models.CharField(
                        blank=True,
                        help_text="A comma-separated list of UCI moves",
                        max_length=150,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^(?:[a-h][1-8][a-h][1-8],){1,}[a-h][1-8][a-h][1-8]$"
                            )
                        ],
                    ),
                ),
                (
                    "fen_before_bot_first_move",
                    models.CharField(editable=False, max_length=90, null=True),
                ),
                (
                    "character_id_by_square_before_bot_first_move",
                    models.JSONField(editable=False, null=True),
                ),
                ("teams", models.JSONField(editable=False, null=True)),
                (
                    "intro_turn_speech_text",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "solution_turns_count",
                    models.PositiveSmallIntegerField(editable=False, null=True),
                ),
            ],
        ),
    ]
