# Generated by Django 4.1.3 on 2023-09-08 21:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []  # type: ignore

    operations = [
        migrations.CreateModel(
            name="DailyChallenge",
            fields=[
                (
                    "id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("fen", models.CharField(max_length=90)),
                ("piece_role_by_square", models.JSONField(editable=False)),
                (
                    "fen_before_bot_first_move",
                    models.CharField(editable=False, max_length=90),
                ),
                (
                    "piece_role_by_square_before_bot_first_move",
                    models.JSONField(editable=False),
                ),
                ("teams", models.JSONField(editable=False)),
                (
                    "bot_first_move",
                    models.CharField(
                        help_text="uses UCI notation, e.g. 'e2e4'", max_length=5
                    ),
                ),
                ("intro_turn_speech_square", models.CharField(max_length=2)),
                (
                    "intro_turn_speech_text",
                    models.CharField(max_length=100, blank=True),
                ),
            ],
        ),
    ]
