# Generated by Django 4.2.5 on 2023-09-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daily_challenge", "0003_dailychallenge_lookup_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailychallenge",
            name="starting_advantage",
            field=models.IntegerField(
                default=0,
                help_text="positive number means the human player has an advantage, negative number means the bot has an advantage",
            ),
        ),
    ]
