# Generated by Django 4.1.3 on 2023-08-28 17:24

from django.db import migrations


def _initialise_starting_advantage(apps, schema_editor):
    from apps.chess.business_logic import compute_game_score

    DailyChallenge = apps.get_model("daily_challenge", "DailyChallenge")
    for challenge in DailyChallenge.objects.filter(starting_advantage=0):
        starting_advantage = compute_game_score(fen=challenge.fen)
        if starting_advantage is None:
            continue  # can happen if the machine is too slow to compute the score 😬
        challenge.starting_advantage = compute_game_score(fen=challenge.fen)
        challenge.save(update_fields=("starting_advantage",))


class Migration(migrations.Migration):

    dependencies = [
        ("daily_challenge", "0004_dailychallenge_starting_advantage"),
    ]

    operations = [
        migrations.RunPython(
            _initialise_starting_advantage, reverse_code=migrations.RunPython.noop
        )
    ]
