# Generated by Django 4.2.5 on 2023-11-03 21:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daily_challenge", "0004_dailychallenge_starting_advantage"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailychallenge",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dailychallenge",
            name="source",
            field=models.CharField(
                help_text="e.g. 'lichess-0009B'", max_length=100, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="dailychallenge",
            name="status",
            field=models.IntegerField(
                choices=[(0, "pending"), (1, "published"), (2, "archived")], default=0
            ),
        ),
        migrations.AddField(
            model_name="dailychallenge",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="dailychallenge",
            name="bot_first_move",
            field=models.CharField(
                help_text="uses UCI notation, e.g. 'e2e4'", max_length=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="dailychallenge",
            name="fen_before_bot_first_move",
            field=models.CharField(editable=False, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name="dailychallenge",
            name="intro_turn_speech_square",
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="dailychallenge",
            name="lookup_key",
            field=models.CharField(
                help_text="e.g. '2021-10-01', or just '10-01' for challenges that can be re-used from a year to the next",
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="dailychallenge",
            name="piece_role_by_square",
            field=models.JSONField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="dailychallenge",
            name="piece_role_by_square_before_bot_first_move",
            field=models.JSONField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="dailychallenge",
            name="starting_advantage",
            field=models.IntegerField(
                help_text="positive number means the human player has an advantage, negative number means the bot has an advantage",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="dailychallenge",
            name="teams",
            field=models.JSONField(editable=False, null=True),
        ),
    ]
