# Generated by Django 5.0.1 on 2024-02-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("daily_challenge", "0006_dailychallengestats"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dailychallengestats",
            options={
                "ordering": ("-day",),
                "verbose_name": "Daily challenge stats",
                "verbose_name_plural": "Daily challenges stats",
            },
        ),
        migrations.AlterField(
            model_name="dailychallengestats",
            name="turns_count",
            field=models.IntegerField(
                default=0, help_text="Number of turns played by players"
            ),
        ),
    ]
