# Generated by Django 5.0.2 on 2024-02-11 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daily_challenge", "0007_alter_dailychallengestats_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailychallenge",
            name="solution",
            field=models.CharField(
                blank=True,
                help_text="A comma-separated list of UCI moves",
                max_length=120,
            ),
        ),
    ]
