# Generated by Django 5.0.2 on 2024-02-12 20:06

from django.db import migrations


def _set_fallback_game_solution(apps, schema_editor):
    DailyChallenge = apps.get_model("daily_challenge", "DailyChallenge")
    challenge = DailyChallenge.objects.get(lookup_key="fallback")
    challenge.solution = (
        "e4f6,f4f6,e5f6,b3d2,f6f7,g8g7,b6d4,g7g6,f3h4,g6g5,d4e5,g5h4,e5g3,h4h5,g3g4"
    )
    challenge.solution_turns_count = 8
    challenge.save()


class Migration(migrations.Migration):

    dependencies = [
        ("daily_challenge", "0008_dailychallenge_solution_and_more"),
    ]

    operations = [migrations.RunPython(_set_fallback_game_solution)]
