# Generated by Django 5.0.2 on 2024-03-19 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daily_challenge", "0012_dailychallengestats_played_challenges_count"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dailychallengestats",
            old_name="played_count",
            new_name="attempts_count",
        ),
        migrations.AlterField(
            model_name="dailychallengestats",
            name="attempts_count",
            field=models.IntegerField(
                default=0,
                help_text="Number of attempts where the player played at least 1 move",
            ),
        ),
    ]
