# Generated by Django 5.1.1 on 2024-09-28 11:00
from typing import TYPE_CHECKING, cast

from django.db import migrations

from apps.chess.consts import PLAYER_SIDES

if TYPE_CHECKING:
    from apps.chess.types import GameTeamsDict


def _convert_existing_games_team_members_to_tuples(apps, schema_editor):
    DailyChallenge = apps.get_model("daily_challenge", "DailyChallenge")

    for challenge in DailyChallenge.objects.filter(teams__isnull=False).iterator():
        teams = cast("GameTeamsDict", challenge.teams)

        if not isinstance(teams["w"][0], dict):
            continue  # this game already uses the new "tuples" format

        for side in PLAYER_SIDES:
            # Convert the list of team-members-as-dicts to a list of tuples
            teams[side] = [tuple(member.values()) for member in teams[side]]

        challenge.save()


class Migration(migrations.Migration):
    dependencies = [
        ("daily_challenge", "0015_dailychallengestats_returning_players_count"),
    ]

    operations = [migrations.RunPython(_convert_existing_games_team_members_to_tuples)]
