# Generated by Django 4.1.3 on 2023-09-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chess", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailychallenge",
            name="piece_role_by_square_before_bot_first_move",
            field=models.JSONField(editable=False),
        ),
    ]
