"""
Django settings.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from __future__ import annotations

from pathlib import Path
from os import environ as env
import dj_database_url

SRC_DIR = Path(__file__).resolve().parent.parent.parent
REPO_ROOT_DIR = SRC_DIR.parent


# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

SECRET_KEY = env.get("SECRET_KEY")

DEBUG = False

ALLOWED_HOSTS: list[str] = []


# Application definition

INSTALLED_APPS = (
    [
        # Django built-in apps:
        "django.contrib.admin",
        "django.contrib.auth",
        "django.contrib.contenttypes",
        "django.contrib.sessions",
        "django.contrib.messages",
        "django.contrib.staticfiles",
    ]
    + [
        # 3rd-party apps:
        "django_alive", # https://github.com/lincolnloop/django-alive
        "django_htmx", # https://django-htmx.readthedocs.io/en/latest/
        "django_google_fonts",  # https://github.com/andymckay/django-google-fonts
    ]
    + [
        # Our own apps:
        "apps.webui",
    ]
)

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        **dj_database_url.config(),
        "OPTIONS": {
            # https://blog.pecar.me/sqlite-django-config#in-django-51-or-newer
            "transaction_mode": "IMMEDIATE",
            "timeout": 5,  # seconds
            "init_command": """
                PRAGMA journal_mode=WAL;
                PRAGMA synchronous=NORMAL;
                PRAGMA mmap_size = 134217728;
                PRAGMA journal_size_limit = 27103364;
                PRAGMA cache_size=2000;
            """,
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-gb"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# File storage
# https://docs.djangoproject.com/en/5.2/ref/settings/#storages
STORAGES = {
    # This is a copy of the Django default value for this setting.
    # We'll alter it in some of our settings modules.
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Google fonts to mirror locally:
# https://github.com/andymckay/django-google-fonts
GOOGLE_FONTS = (
    "Open Sans:ital,wght@0,300..800;1,300..800",  # https://fonts.google.com/specimen/Open+Sans
)
GOOGLE_FONTS_DIR = REPO_ROOT_DIR / "src" / "apps" / "webui" / "static" / "webui" / "google-fonts"
GOOGLE_FONTS_URL = f"/{STATIC_URL}webui/google-fonts/fonts/"

# Our custom settings:
ZAKUCHESS_VERSION = env.get("ZAKUCHESS_VERSION", "dev")
MASTODON_PAGE = env.get("MASTODON_PAGE")
CANONICAL_URL = env.get("CANONICAL_URL", "https://zakuchess.com/")
